apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackathon-starter-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hackathon-starter-app
  template:
    metadata:
      labels:
        app: hackathon-starter-app
    spec:
      containers:
        - name: hackathon-starter-app
          image: vimalshero/hackathon-starter:1.0.0-4
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: "500m"
          ports:
            - containerPort: 3000
