apiVersion: v1
kind: Service
metadata:
  name: hackathon-starter-service
  labels:
    app: hackathon-starter-app 
spec:
  selector:
    app: hackathon-starter-app

  ports:
    - port: 3000
      targetPort: 3000

  type: LoadBalancer
